language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - composer global require hirak/prestissimo
  - composer install --no-interaction --no-suggest

script: vendor/bin/phpunit
