language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - CC_TEST_REPORTER_ID=532d65f9f3a84389bafa028bb77022b7b4ad082e07fd89b519b7e7f63ccd7fc6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: nightly

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Initialise Composer
  - composer self-update -q
  - composer global require hirak/prestissimo

  # Installing Composer dependencies
  - composer install --no-interaction --no-suggest --optimize-autoloader

  # Installing code coverage tools
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

script: vendor/bin/paratest --coverage-clover clover.xml
