language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - hhvm-nightly
  - nightly

env:
  - RAILT_DEBUG=1
  - APP_ENV=testing

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - pecl install -f parle
  - echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update -q
  - composer global require hirak/prestissimo
  - composer install --no-interaction --no-suggest

script: vendor/bin/phpunit
